config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users
  root to: "games#index"

  resources :shapes, param: :name, :only => [:index, :show], :defaults => { :format => 'json' }
  resources :transforms, param: :name, :only => [:index, :show], :defaults => { :format => 'json' }
  resources :colours, param: :index, :only => [:index, :show], :defaults => { :format => 'json' }

  resources :games, :except => [:edit, :destroy, :update] do
    resources :turns, :only => [:index, :create], :defaults => { :format => 'json' }
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :turns, through: :players
	has_many :players, dependent: :destroy

	validates :players, presence: true

	def shapes
		Shapes.shapes
	end

	def colours
		Colours.colours
	end

  def active_colour
    colour_index = turns.size % 4
    colours[colour_index]
  end

  def active_player
    player_index = turns.size % 4
    players.play_order[player_index]
  end

  def finished?
    has_more_than_four_turns = turns.size > 4
    last_four_turns_are_passes = turns.reverse_play_order.limit(4).all? { |turn| turn.pass? }
    has_more_than_four_turns && last_four_turns_are_passes
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :game

  has_many :turns, dependent: :destroy

  validates :user, :game, presence: true

  delegate :name, to: :user

  scope :play_order, -> { order(created_at: :asc, id: :asc) }
end

app/models/turn.rb
class Turn < ActiveRecord::Base
	belongs_to :player

	validates :player, presence: true
	validates :shape, shape: true
	validates :shape, presence: true, if: :has_shape_or_transform?
	validates :transform, transform: true
	validates :transform, presence: true, if: :has_shape_or_transform?
	validates :x, :y, absence: true, unless: :has_shape_or_transform?
	validates :x, :y,
		inclusion: { in: 0...Board::DEFAULT_SIZE }, 
		numericality: { only_integer: true }, 
		if: :has_shape_or_transform?

	scope :play_order, -> { order(created_at: :asc, id: :asc) }
	scope :reverse_play_order, -> { order(created_at: :desc, id: :desc) }

	def position
		@position ||= Point.new(x, y)
	end

	def has_shape_or_transform?
		shape.present? || transform.present?
	end

	def pass?
		!shape.present? && !transform.present?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

  has_many :players, dependent: :destroy
	has_many :games, through: :players

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController
	def index
		@colours = Colours.colours

		render json: @colours
	end

	def show
		@colour = load_colour

		render json: @colour
	end

	private

	def load_colour
		Colours.colours[params.require(:index).to_i]
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def index
		@lobby = LobbyPresenter.new(current_user)
	end

	def show
		load_game
		load_player

		if request.format == :json
			@presenter = GamePresenter.new(@player)
		end
	end

	def new
		@game = Game.new
		@opponents = User.where.not(id: current_user)
	end

	def create
		form_object = CreateGameFormObject.new(params)

		if form_object.valid?
			new_game = StartNewGame.new(current_user,
				form_object.player_two_user_id, 
				form_object.player_three_user_id, 
				form_object.player_four_user_id).call
			redirect_to new_game
		else
			flash[:error] = "You must select three different players to join the game"
			redirect_to new_game_url
		end
	end

	private 

	def load_player
		@player = current_user.players.find_by!(game_id: @game.id)
	end

	def load_game
		@game = current_user.games.find_by!(id: game_id)
	end

	def game_id
		params.require(:id)
	end
end

app/controllers/shapes_controller.rb
class ShapesController < ApplicationController
	def index
		@shapes = Shapes.shapes
	end

	def show
		@shape = load_shape
	end

	private

	def load_shape
		Shapes[params.require(:name)]
	end
end

app/controllers/transforms_controller.rb
class TransformsController < ApplicationController
	def index
		@transforms = Transforms.transforms
	end

	def show
		@transform = load_transform
	end

	private

	def load_transform
		Transforms[params.require(:name)]
	end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  before_action :load_player
  before_action :load_game

  def index
    @turns = @game.turns.play_order
  end

  def create
    create_turn_params = CreateTurnFormObject.new(params)
    if create_turn_params.valid?
      created = PlayPiece.new(@player, create_turn_params.coordinates).call
      if created
        WebsocketRails[websocket_channel_name].trigger(:update, { :updated => true })
        @message = "OK"
      else
        @message = "Failed to create turn for player #{@player.name}. PlayPiece failed."
        render :create, :status => :internal_server_error
      end
    else
      @message = "Failed to create turn for player #{@player.name}. Invalid params."
      render :create, :status => :internal_server_error
    end
  end

  private

  def load_player
    @player = current_user.players.find_by!(game_id: game_id)
  end

  def load_game
    @game = @player.game
  end

  def game_id
    params.require(:game_id)
  end

  def websocket_channel_name
    ("game_"+@game.id.to_s).to_sym
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def meta_game_id(game)
    content_for :meta_game_id, game.id.to_s
  end
end

app/views/games/index.html.erb
<h1>Lobby (<%= current_user.name %>)</h1>

<h3>Games</h3>

<table>
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th>Player One</th>
			<th>Player Two</th>
			<th>Player Three</th>
			<th>Player Four</th>
		</tr>
	</thead>
	<% @lobby.games.each do |game| %>
		<tr>
			<td><%= link_to 'Play', game_path(game) %></td>
			<td><%= game.players[0].name %></td>
			<td><%= game.players[1].name %></td>
			<td><%= game.players[2].name %></td>
			<td><%= game.players[3].name %></td>
		</tr>
	<% end %>
</table>

<br />
<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= form_for(@game) do |f| %>

	<div>
		<%= label_tag 'creator', "Player one: " %>
		<span><%= current_user.name %></span>
	</div>

	<% %w(two three four).each do |player_number| %>
	  <div>
	    <%= label_tag 'player_'+player_number+'_user_id', "Player "+player_number+": " %>
	    <%= select_tag "player_"+player_number+"_user_id", options_from_collection_for_select(@opponents, "id", "name") %>
	  </div>
	<% end %>

	<br />

  <div>
    <%= f.submit %>
  </div>
<% end %>

<br />
<br />

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<% meta_game_id @game %>

<div id="wrapper">
	<header>
		<nav></nav>
	</header>

	<div id="content">
		<div id="scores"></div> 
		<div id="board"></div>
	</div> 
	<div id="rightcol">
		<h2><%= current_user.name %></h2>
		<div id="gameover"></div>
		<div id="controls"></div>
		<div id="pieces"></div>
	</div> 
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blokus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if content_for?(:meta_game_id) %>
    <meta name="blokus_game_id" content="<%= yield(:meta_game_id) %>" />
  <% end %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>